USE [master]
GO

--alter names/strings/etc. to suit your environment

CREATE DATABASE [ArchiveDBName] ON  PRIMARY 
( NAME = N'ArchiveDBName', FILENAME = N'X:\ArchiveDBName.mdf' , SIZE = 104857600KB , MAXSIZE = UNLIMITED, FILEGROWTH = 2097152KB )
 LOG ON 
( NAME = N'ArchiveDBName_log', FILENAME = N'X:\ArchiveDBName_log.ldf' , SIZE = 6291456KB , MAXSIZE = 2048GB , FILEGROWTH = 1048576KB )
GO

ALTER DATABASE [ArchiveDBName] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ArchiveDBName].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ArchiveDBName] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ArchiveDBName] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ArchiveDBName] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ArchiveDBName] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ArchiveDBName] SET ARITHABORT OFF 
GO

ALTER DATABASE [ArchiveDBName] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ArchiveDBName] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ArchiveDBName] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ArchiveDBName] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ArchiveDBName] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ArchiveDBName] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ArchiveDBName] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ArchiveDBName] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ArchiveDBName] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ArchiveDBName] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ArchiveDBName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ArchiveDBName] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ArchiveDBName] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ArchiveDBName] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ArchiveDBName] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ArchiveDBName] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ArchiveDBName] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ArchiveDBName] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ArchiveDBName] SET  MULTI_USER 
GO

ALTER DATABASE [ArchiveDBName] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ArchiveDBName] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ArchiveDBName] SET  READ_WRITE 
GO



